export const actionTypes = {
  FETCH_MOVIES: "FETCH_MOVIES",
  FETCH_POPULAR_MOVIES: "FETCH_POPULAR_MOVIES",
  FETCH_TV_SHOWS: "FETCH_TV_SHOWS",
  FETCH_NOW_PLAYING: "FETCH_NOW_PLAYING",
  ADD_MOVIE_TO_FAVOURITE: "ADD_MOVIE_TO_FAVOURITE",
  ADD_POPULAR_MOVIE_TO_FAVOURITE: "ADD_POPULAR_MOVIE_TO_FAVOURITE",
  ADD_TV_SHOW_TO_FAVOURITE: "ADD_TV_SHOW_TO_FAVOURITE",
  ADD_NOW_PLAYING_TO_FAVOURITE: "ADD_NOW_PLAYING_TO_FAVOURITE",
  REMOVE_MOVIE_FROM_FAVOURITE: "REMOVE_MOVIE_TO_FAVOURITE",
};
